"use client"

import React, { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import Link from 'next/link'
import { MagicUIProvider, MagicUI, MagicUIPage } from '@/components/magic-ui';

const showcaseTheme = {
  primary: '#6366f1',
  secondary: '#f59e42',
  background: 'linear-gradient(135deg, #f0f4ff 0%, #e0e7ff 100%)',
  text: '#111827',
  border: '#e5e7eb',
  radius: '1.25rem',
  spacing: '1.5rem',
};

const showcasePRD = `\n# MagicUI Showcase\nA collection of real-world UI use cases generated by MagicUI. Each example demonstrates a different capability of the package.`;

const showcaseExamples = [
  {
    title: 'Product Card',
    description: 'Show a product card with product name ({{name}}), price (${{price}}), and image ({{image}}). The image should have a fallback to https://placehold.co/300x200 if it fails to load.',
    data: {
      name: 'Noise Cancelling Headphones',
      price: 129.99,
      image: 'https://example.com/nonexistent-headphones.jpg',
    },
    id: 'showcase-product-card',
    moduleName: 'product-card',
    code: `<MagicUI\n  id="showcase-product-card"\n  moduleName="product-card"\n  description="Show a product card with product name ({{name}}), price (\${{price}}), and image ({{image}}). The image should have a fallback to https://placehold.co/300x200 if it fails to load."\n  data={{ name: 'Noise Cancelling Headphones', price: 129.99, image: 'https://example.com/nonexistent-headphones.jpg' }}\n/>`
  },
  {
    title: 'User Profile',
    description: 'Display a user profile with avatar ({{avatar}}), name ({{name}}), and status ({{status}}). Avatar should fallback to https://placehold.co/100x100.',
    data: {
      name: 'Jane Doe',
      status: 'online',
      avatar: 'https://example.com/nonexistent-avatar.png',
    },
    id: 'showcase-user-profile',
    moduleName: 'user-profile',
    code: `<MagicUI\n  id="showcase-user-profile"\n  moduleName="user-profile"\n  description="Display a user profile with avatar ({{avatar}}), name ({{name}}), and status ({{status}}). Avatar should fallback to https://placehold.co/100x100."\n  data={{ name: 'Jane Doe', status: 'online', avatar: 'https://example.com/nonexistent-avatar.png' }}\n/>`
  },
  {
    title: 'Analytics Widget',
    description: 'Show a dashboard widget with metric ({{metric}}), value ({{value}}), and trend ({{trend}}).',
    data: {
      metric: 'Active Users',
      value: 1240,
      trend: '+5.2%',
    },
    id: 'showcase-analytics-widget',
    moduleName: 'analytics-widget',
    code: `<MagicUI\n  id="showcase-analytics-widget"\n  moduleName="analytics-widget"\n  description="Show a dashboard widget with metric ({{metric}}), value ({{value}}), and trend ({{trend}})."\n  data={{ metric: 'Active Users', value: 1240, trend: '+5.2%' }}\n/>`
  },
  {
    title: 'Task List (Complex)',
    description: 'Display a list of tasks with title ({{title}}), due date ({{dueDate}}), completed ({{completed}}), and subtasks ({{subtasks}}). Show nested subtasks if present.',
    data: [
      { title: 'Design homepage', dueDate: '2024-06-10', completed: false, subtasks: [{ title: 'Header', completed: true }, { title: 'Footer', completed: false }] },
      { title: 'Write docs', dueDate: '2024-06-12', completed: true, subtasks: [] },
      { title: 'Release v1.0', dueDate: '2024-06-15', completed: false, subtasks: [{ title: 'Beta', completed: true }, { title: 'Launch', completed: false }] },
    ],
    id: 'showcase-task-list',
    moduleName: 'task-list',
    code: `<MagicUI\n  id="showcase-task-list"\n  moduleName="task-list"\n  description="Display a list of tasks with title ({{title}}), due date ({{dueDate}}), completed ({{completed}}), and subtasks ({{subtasks}}). Show nested subtasks if present."\n  data={[ /* ...see source for nested data... */ ]}\n/>`
  },
  {
    title: 'Chat Message (Complex)',
    description: 'Show a chat message with sender ({{sender}}), message ({{message}}), timestamp ({{timestamp}}), and attachments ({{attachments}}). If attachments are present, show them as downloadable links.',
    data: {
      sender: 'Support Bot',
      message: 'Here is your requested file.',
      timestamp: '10:42 AM',
      attachments: [
        { name: 'invoice.pdf', url: 'https://example.com/invoice.pdf' },
        { name: 'screenshot.png', url: 'https://example.com/screenshot.png' }
      ]
    },
    id: 'showcase-chat-message',
    moduleName: 'chat-message',
    code: `<MagicUI\n  id="showcase-chat-message"\n  moduleName="chat-message"\n  description="Show a chat message with sender ({{sender}}), message ({{message}}), timestamp ({{timestamp}}), and attachments ({{attachments}}). If attachments are present, show them as downloadable links."\n  data={{ sender: 'Support Bot', message: 'Here is your requested file.', timestamp: '10:42 AM', attachments: [ { name: 'invoice.pdf', url: 'https://example.com/invoice.pdf' }, { name: 'screenshot.png', url: 'https://example.com/screenshot.png' } ] }}\n/>`
  },
  {
    title: 'Custom Form (Complex)',
    description: 'Create a form with fields: name ({{name}}), email ({{email}}), message ({{message}}), and a dynamic list of tags ({{tags}}).',
    data: {
      name: '',
      email: '',
      message: '',
      tags: ['feature', 'bug', 'question']
    },
    id: 'showcase-custom-form',
    moduleName: 'custom-form',
    code: `<MagicUI\n  id="showcase-custom-form"\n  moduleName="custom-form"\n  description="Create a form with fields: name ({{name}}), email ({{email}}), message ({{message}}), and a dynamic list of tags ({{tags}})."\n  data={{ name: '', email: '', message: '', tags: ['feature', 'bug', 'question'] }}\n/>`
  },
];

function ExampleTabs({ code, children }: { code: string, children: React.ReactNode }) {
  const [tab, setTab] = useState<'code' | 'preview'>('preview');
  return (
    <div>
      <div className="flex space-x-2 mb-2">
        <Button size="sm" variant={tab === 'preview' ? 'default' : 'outline'} onClick={() => setTab('preview')}>Preview</Button>
        <Button size="sm" variant={tab === 'code' ? 'default' : 'outline'} onClick={() => setTab('code')}>Code</Button>
      </div>
      <div className="rounded-lg border bg-white p-4 min-h-[180px]">
        {tab === 'preview' ? children : (
          <pre className="text-xs font-mono whitespace-pre-wrap text-gray-800">{code}</pre>
        )}
      </div>
    </div>
  );
}

export default function HomeShowcasePage() {
  return (
    <MagicUIProvider theme={showcaseTheme} projectPrd={showcasePRD}>
      <div className="relative min-h-screen bg-gradient-to-br from-indigo-100 via-blue-50 to-white overflow-x-hidden">
        {/* Decorative SVG background */}
        <svg className="absolute top-0 left-1/2 -translate-x-1/2 z-0 opacity-30 blur-2xl" width="1200" height="400" viewBox="0 0 1200 400" fill="none" xmlns="http://www.w3.org/2000/svg">
          <ellipse cx="600" cy="200" rx="600" ry="200" fill="url(#paint0_radial)" />
          <defs>
            <radialGradient id="paint0_radial" cx="0" cy="0" r="1" gradientTransform="translate(600 200) scale(600 200)" gradientUnits="userSpaceOnUse">
              <stop stopColor="#a5b4fc" />
              <stop offset="1" stopColor="#f0f4ff" stopOpacity="0" />
            </radialGradient>
          </defs>
        </svg>
        {/* Navigation / Hero */}
        <nav className="w-full bg-white/60 backdrop-blur-md border-b shadow-md sticky top-0 z-20 rounded-b-2xl">
          <div className="max-w-6xl mx-auto flex justify-between items-center px-4 py-3">
            <div className="font-extrabold text-2xl text-indigo-700 tracking-tight drop-shadow-sm">MagicUI</div>
            <div className="flex gap-4">
              <Link href="/playground"><Button variant="outline" className="transition-all hover:scale-105 hover:shadow-lg">Playground</Button></Link>
              <Link href="/magic-ui-demo/full-page"><Button variant="outline" className="transition-all hover:scale-105 hover:shadow-lg">Full Page Demo</Button></Link>
            </div>
          </div>
        </nav>
        <header className="relative py-20 sm:py-28 bg-gradient-to-br from-indigo-200/80 via-blue-100/80 to-white border-b mb-14 shadow-lg rounded-b-3xl overflow-hidden z-10">
          <div className="absolute -top-20 left-1/2 -translate-x-1/2 w-[700px] h-[300px] bg-gradient-to-tr from-indigo-300/40 via-blue-200/30 to-white rounded-full blur-3xl opacity-60 z-0" />
          <div className="max-w-4xl mx-auto text-center px-4 relative z-10">
            <h1 className="text-5xl sm:text-6xl font-extrabold mb-5 text-indigo-900 drop-shadow-lg tracking-tight">Build UIs with AI, Instantly</h1>
            <p className="text-lg sm:text-xl text-gray-700 mb-8 font-medium">MagicUI generates beautiful, production-ready React components and pages from your data and requirements. See code and preview for every use case.</p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link href="/playground"><Button size="lg" className="bg-indigo-600 hover:bg-indigo-700 text-white shadow-xl transition-all hover:scale-105">Try Playground</Button></Link>
              <Link href="/magic-ui-demo/full-page"><Button size="lg" variant="outline" className="border-indigo-400 text-indigo-700 hover:bg-indigo-50 shadow-md transition-all hover:scale-105">Full Page Example</Button></Link>
            </div>
          </div>
        </header>
        <main className="max-w-5xl mx-auto space-y-16 px-2 pb-24 z-10 relative">
          <h2 className="text-4xl font-extrabold text-center mb-10 text-indigo-800 tracking-tight">Awesome Examples</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
            {showcaseExamples.map((ex) => (
              <Card key={ex.id} className="overflow-visible shadow-xl border-0 bg-white/90 backdrop-blur-md transition-all hover:scale-[1.02] hover:shadow-2xl">
                <CardHeader>
                  <CardTitle className="text-lg font-bold text-indigo-700">{ex.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <ExampleTabs code={ex.code}>
                    <MagicUI
                      id={ex.id}
                      moduleName={ex.moduleName}
                      description={ex.description}
                      data={ex.data}
                      className="w-full"
                    />
                  </ExampleTabs>
                </CardContent>
              </Card>
            ))}
          </div>
          {/* Full Page Demo */}
          <Card className="mt-20 border-blue-300 bg-gradient-to-br from-blue-100 to-indigo-50 shadow-xl">
            <CardHeader>
              <CardTitle className="text-lg font-bold text-indigo-700">Full Page Demo</CardTitle>
            </CardHeader>
            <CardContent>
              <ExampleTabs code={`<MagicUIPage\n  id=\"showcase-landing-page\"\n  moduleName=\"LandingPage\"\n  description=\"A beautiful landing page for a SaaS product. Use modern layout, hero section, and call to action.\"\n  data={{}}\n/>`}>
                <Link href="/magic-ui-demo/full-page" className="text-blue-700 underline font-semibold mb-2" target="_blank">View Full Page Example</Link>
                <MagicUIPage
                  id="showcase-landing-page"
                  moduleName="LandingPage"
                  description={'A beautiful landing page for a SaaS product. Use modern layout, hero section, and call to action.'}
                  data={{}}
                  className="w-full border rounded-lg"
                />
              </ExampleTabs>
            </CardContent>
          </Card>
        </main>
      </div>
    </MagicUIProvider>
  )
}
