"use client"

import type React from "react"
import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import Link from "next/link"
import { MagicUIProvider, MagicUI, MagicUIPage } from "@/components/magic-ui"

const showcaseTheme = {
  primary: "#10b981",
  secondary: "#f59e0b",
  background: "linear-gradient(135deg, #ecfdf5 0%, #d1fae5 100%)",
  text: "#064e3b",
  border: "#a7f3d0",
  radius: "1.25rem",
  spacing: "1.5rem",
}

const showcasePRD = `\n# MagicUI Showcase - Emerald Edition\nA collection of real-world UI use cases generated by MagicUI. Each example demonstrates a different capability of the package with a beautiful emerald theme.`

const showcaseExamples = [
  {
    title: "Product Card",
    description:
      "Show a product card with product name ({{name}}), price (${{price}}), and image ({{image}}). The image should have a fallback to https://placehold.co/300x200 if it fails to load.",
    data: {
      name: "Eco-Friendly Bamboo Speaker",
      price: 89.99,
      image: "https://example.com/nonexistent-speaker.jpg",
    },
    id: "showcase-product-card",
    moduleName: "product-card",
    code: `<MagicUI\n  id="showcase-product-card"\n  moduleName="product-card"\n  description="Show a product card with product name ({{name}}), price (\${{price}}), and image ({{image}}). The image should have a fallback to https://placehold.co/300x200 if it fails to load."\n  data={{ name: 'Eco-Friendly Bamboo Speaker', price: 89.99, image: 'https://example.com/nonexistent-speaker.jpg' }}\n/>`,
  },
  {
    title: "User Profile",
    description:
      "Display a user profile with avatar ({{avatar}}), name ({{name}}), and status ({{status}}). Avatar should fallback to https://placehold.co/100x100.",
    data: {
      name: "Alex Green",
      status: "online",
      avatar: "https://example.com/nonexistent-avatar.png",
    },
    id: "showcase-user-profile",
    moduleName: "user-profile",
    code: `<MagicUI\n  id="showcase-user-profile"\n  moduleName="user-profile"\n  description="Display a user profile with avatar ({{avatar}}), name ({{name}}), and status ({{status}}). Avatar should fallback to https://placehold.co/100x100."\n  data={{ name: 'Alex Green', status: 'online', avatar: 'https://example.com/nonexistent-avatar.png' }}\n/>`,
  },
  {
    title: "Analytics Widget",
    description: "Show a dashboard widget with metric ({{metric}}), value ({{value}}), and trend ({{trend}}).",
    data: {
      metric: "Green Energy Saved",
      value: "2.4kWh",
      trend: "+12.8%",
    },
    id: "showcase-analytics-widget",
    moduleName: "analytics-widget",
    code: `<MagicUI\n  id="showcase-analytics-widget"\n  moduleName="analytics-widget"\n  description="Show a dashboard widget with metric ({{metric}}), value ({{value}}), and trend ({{trend}})."\n  data={{ metric: 'Green Energy Saved', value: '2.4kWh', trend: '+12.8%' }}\n/>`,
  },
  {
    title: "Task List (Complex)",
    description:
      "Display a list of tasks with title ({{title}}), due date ({{dueDate}}), completed ({{completed}}), and subtasks ({{subtasks}}). Show nested subtasks if present.",
    data: [
      {
        title: "Plant office garden",
        dueDate: "2024-06-10",
        completed: false,
        subtasks: [
          { title: "Buy seeds", completed: true },
          { title: "Setup planters", completed: false },
        ],
      },
      { title: "Sustainability report", dueDate: "2024-06-12", completed: true, subtasks: [] },
      {
        title: "Green initiative launch",
        dueDate: "2024-06-15",
        completed: false,
        subtasks: [
          { title: "Team training", completed: true },
          { title: "Public announcement", completed: false },
        ],
      },
    ],
    id: "showcase-task-list",
    moduleName: "task-list",
    code: `<MagicUI\n  id="showcase-task-list"\n  moduleName="task-list"\n  description="Display a list of tasks with title ({{title}}), due date ({{dueDate}}), completed ({{completed}}), and subtasks ({{subtasks}}). Show nested subtasks if present."\n  data={[ /* ...see source for nested data... */ ]}\n/>`,
  },
  {
    title: "Chat Message (Complex)",
    description:
      "Show a chat message with sender ({{sender}}), message ({{message}}), timestamp ({{timestamp}}), and attachments ({{attachments}}). If attachments are present, show them as downloadable links.",
    data: {
      sender: "EcoBot Assistant",
      message: "Here are your sustainability metrics and carbon footprint report.",
      timestamp: "2:15 PM",
      attachments: [
        { name: "carbon-report.pdf", url: "https://example.com/carbon-report.pdf" },
        { name: "energy-usage.xlsx", url: "https://example.com/energy-usage.xlsx" },
      ],
    },
    id: "showcase-chat-message",
    moduleName: "chat-message",
    code: `<MagicUI\n  id="showcase-chat-message"\n  moduleName="chat-message"\n  description="Show a chat message with sender ({{sender}}), message ({{message}}), timestamp ({{timestamp}}), and attachments ({{attachments}}). If attachments are present, show them as downloadable links."\n  data={{ sender: 'EcoBot Assistant', message: 'Here are your sustainability metrics and carbon footprint report.', timestamp: '2:15 PM', attachments: [ { name: 'carbon-report.pdf', url: 'https://example.com/carbon-report.pdf' }, { name: 'energy-usage.xlsx', url: 'https://example.com/energy-usage.xlsx' } ] }}\n/>`,
  },
  {
    title: "Custom Form (Complex)",
    description:
      "Create a form with fields: name ({{name}}), email ({{email}}), message ({{message}}), and a dynamic list of tags ({{tags}}).",
    data: {
      name: "",
      email: "",
      message: "",
      tags: ["sustainability", "eco-friendly", "green-tech"],
    },
    id: "showcase-custom-form",
    moduleName: "custom-form",
    code: `<MagicUI\n  id="showcase-custom-form"\n  moduleName="custom-form"\n  description="Create a form with fields: name ({{name}}), email ({{email}}), message ({{message}}), and a dynamic list of tags ({{tags}})."\n  data={{ name: '', email: '', message: '', tags: ['sustainability', 'eco-friendly', 'green-tech'] }}\n/>`,
  },
]

function ExampleTabs({ code, children }: { code: string; children: React.ReactNode }) {
  const [tab, setTab] = useState<"code" | "preview">("preview")
  return (
    <div>
      <div className="flex space-x-2 mb-2">
        <Button
          size="sm"
          variant={tab === "preview" ? "default" : "outline"}
          onClick={() => setTab("preview")}
          className="bg-emerald-600 hover:bg-emerald-700 text-white"
        >
          Preview
        </Button>
        <Button
          size="sm"
          variant={tab === "code" ? "default" : "outline"}
          onClick={() => setTab("code")}
          className={
            tab === "code"
              ? "bg-emerald-600 hover:bg-emerald-700 text-white"
              : "border-emerald-300 text-emerald-700 hover:bg-emerald-50"
          }
        >
          Code
        </Button>
      </div>
      <div className="rounded-lg border border-emerald-200 bg-gradient-to-br from-emerald-50 to-green-50 p-4 min-h-[180px] shadow-inner">
        {tab === "preview" ? (
          children
        ) : (
          <pre className="text-xs font-mono whitespace-pre-wrap text-emerald-800 bg-white/60 p-3 rounded border border-emerald-200">
            {code}
          </pre>
        )}
      </div>
    </div>
  )
}

export default function EmeraldShowcasePage() {
  return (
    <MagicUIProvider theme={showcaseTheme} projectPrd={showcasePRD}>
      <div className="relative min-h-screen bg-gradient-to-br from-emerald-100 via-green-50 to-teal-50 overflow-x-hidden">
        {/* Decorative SVG background */}
       

        {/* Floating decorative elements */}
        <div className="absolute top-20 left-10 w-20 h-20 bg-gradient-to-br from-emerald-300 to-green-400 rounded-full opacity-20 blur-xl animate-pulse"></div>
        <div className="absolute top-40 right-20 w-32 h-32 bg-gradient-to-br from-teal-300 to-emerald-400 rounded-full opacity-15 blur-2xl animate-pulse delay-1000"></div>
        <div className="absolute bottom-40 left-1/4 w-24 h-24 bg-gradient-to-br from-green-300 to-emerald-500 rounded-full opacity-25 blur-xl animate-pulse delay-500"></div>

        {/* Navigation / Hero */}
        <nav className="w-full bg-white/70 backdrop-blur-xl border-b border-emerald-200 shadow-lg sticky top-0 z-20 rounded-b-3xl">
          <div className="max-w-6xl mx-auto flex justify-between items-center px-4 py-4">
            <div className="font-extrabold text-3xl bg-gradient-to-r from-emerald-600 to-green-600 bg-clip-text text-transparent tracking-tight drop-shadow-sm">
              ✨ MagicUI
            </div>
            <div className="flex gap-4">
              <Link href="/playground">
                <Button
                  variant="outline"
                  className="border-emerald-300 text-emerald-700 hover:bg-emerald-50 transition-all hover:scale-105 hover:shadow-lg backdrop-blur-sm"
                >
                  🎮 Playground
                </Button>
              </Link>
              <Link href="/magic-ui-demo/full-page">
                <Button className="bg-gradient-to-r from-emerald-600 to-green-600 hover:from-emerald-700 hover:to-green-700 text-white transition-all hover:scale-105 hover:shadow-xl">
                  🚀 Full Demo
                </Button>
              </Link>
            </div>
          </div>
        </nav>

        <header className="relative py-24 sm:py-32 bg-gradient-to-br from-emerald-200/90 via-green-100/90 to-teal-100/80 border-b border-emerald-200 mb-16 shadow-2xl rounded-b-[3rem] overflow-hidden z-10">
          <div className="absolute -top-32 left-1/2 -translate-x-1/2 w-[800px] h-[400px] bg-gradient-to-tr from-emerald-300/50 via-green-200/40 to-teal-200/30 rounded-full blur-3xl opacity-70 z-0" />
          <div className="absolute top-10 right-10 w-40 h-40 bg-gradient-to-br from-emerald-400/30 to-green-500/20 rounded-full blur-2xl opacity-60" />
          <div className="absolute bottom-10 left-10 w-60 h-60 bg-gradient-to-br from-teal-400/20 to-emerald-500/30 rounded-full blur-3xl opacity-50" />

          <div className="max-w-5xl mx-auto text-center px-4 relative z-10">
            <div className="inline-flex items-center gap-2 bg-white/60 backdrop-blur-sm border border-emerald-200 rounded-full px-6 py-2 mb-6 shadow-lg">
              <span className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse"></span>
              <span className="text-emerald-700 font-semibold text-sm">AI-Powered • Real-time • Beautiful</span>
            </div>

            <h1 className="text-6xl sm:text-7xl font-black mb-6 bg-gradient-to-r from-emerald-800 via-green-700 to-teal-700 bg-clip-text text-transparent drop-shadow-lg tracking-tight leading-tight">
              Build UIs with AI,
              <br />
              <span className="text-5xl sm:text-6xl">Instantly ⚡</span>
            </h1>

            <p className="text-xl sm:text-2xl text-emerald-800/80 mb-10 font-medium max-w-3xl mx-auto leading-relaxed">
              MagicUI generates stunning, production-ready React components from your data and requirements.
              <span className="block mt-2 text-lg text-emerald-700">Experience the future of UI development.</span>
            </p>

            <div className="flex flex-col sm:flex-row gap-6 justify-center">
              <Link href="/playground">
                <Button
                  size="lg"
                  className="bg-gradient-to-r from-emerald-600 to-green-600 hover:from-emerald-700 hover:to-green-700 text-white shadow-2xl transition-all hover:scale-110 transform px-8 py-4 text-lg font-semibold rounded-2xl"
                >
                  🎨 Try Playground
                </Button>
              </Link>
              <Link href="/magic-ui-demo/full-page">
                <Button
                  size="lg"
                  variant="outline"
                  className="border-2 border-emerald-400 text-emerald-700 hover:bg-emerald-50 shadow-xl transition-all hover:scale-110 backdrop-blur-sm px-8 py-4 text-lg font-semibold rounded-2xl"
                >
                  🌟 View Examples
                </Button>
              </Link>
            </div>
          </div>
        </header>

        <main className="max-w-6xl mx-auto space-y-20 px-4 pb-32 z-10 relative">
          <div className="text-center mb-16">
            <h2 className="text-5xl font-black mb-4 bg-gradient-to-r from-emerald-800 to-green-700 bg-clip-text text-transparent tracking-tight">
              ✨ Awesome Examples
            </h2>
            <p className="text-xl text-emerald-700/80 max-w-2xl mx-auto">
              Discover the power of AI-generated UI components with these real-world examples
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {showcaseExamples.map((ex, index) => (
              <Card
                key={ex.id}
                className="group overflow-visible shadow-2xl border-0 bg-gradient-to-br from-white/95 to-emerald-50/80 backdrop-blur-xl transition-all duration-500 hover:scale-[1.03] hover:shadow-3xl hover:-translate-y-2 rounded-3xl"
              >
                <CardHeader className="pb-4">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 bg-gradient-to-br from-emerald-500 to-green-600 rounded-full flex items-center justify-center text-white font-bold text-sm shadow-lg">
                      {index + 1}
                    </div>
                    <CardTitle className="text-xl font-bold bg-gradient-to-r from-emerald-700 to-green-700 bg-clip-text text-transparent">
                      {ex.title}
                    </CardTitle>
                  </div>
                </CardHeader>
                <CardContent>
                  <ExampleTabs code={ex.code}>
                    <div className="relative">
                      <MagicUI
                        id={ex.id}
                        moduleName={ex.moduleName}
                        description={ex.description}
                        data={ex.data}
                        className="w-full"
                        {...(ex.id === "showcase-task-list"
                          ? {
                              // Pass an event descriptor for testing AI event handler
                              aiProps: {
                                onTaskComplete: {
                                  func: (task:string)=>{console.log(task); alert("ss")},
                                  description: "Alert when a task is completed",
                                  params: ["task"],
                                },
                              },
                            }
                          : {})}
                      />
                    </div>
                  </ExampleTabs>
                </CardContent>
              </Card>
            ))}
          </div>

          {/* Full Page Demo */}
          <Card className="mt-24 border-2 border-emerald-300 bg-gradient-to-br from-emerald-100/80 to-green-50/80 shadow-2xl backdrop-blur-sm rounded-3xl overflow-hidden">
            <CardHeader className="bg-gradient-to-r from-emerald-600 to-green-600 text-white">
              <CardTitle className="text-2xl font-bold flex items-center gap-3">
                <span className="text-3xl">🌟</span>
                Full Page Demo - Complete Experience
              </CardTitle>
            </CardHeader>
            <CardContent className="p-8">
              <ExampleTabs
                code={`<MagicUIPage\n  id=\"showcase-landing-page\"\n  moduleName=\"EcoLandingPage\"\n  description=\"A beautiful eco-friendly landing page for a sustainable SaaS product. Use modern green design, hero section, and environmental call to action.\"\n  data={{}}\n/>`}
              >
                <div className="space-y-4">
                  <Link
                    href="/magic-ui-demo/full-page"
                    className="inline-flex items-center gap-2 text-emerald-700 hover:text-emerald-800 underline font-bold text-lg transition-colors"
                    target="_blank"
                  >
                    🚀 View Full Page Experience
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
                      />
                    </svg>
                  </Link>
                  <div className="border-2 border-emerald-200 rounded-2xl overflow-hidden shadow-inner bg-white/50">
                    <MagicUIPage
                      id="showcase-landing-page"
                      moduleName="EcoLandingPage"
                      description={
                        "A beautiful eco-friendly landing page for a sustainable SaaS product. Use modern green design, hero section, and environmental call to action."
                      }
                      data={{}}
                      // className="w-full"
                    />
                  </div>
                </div>
              </ExampleTabs>
            </CardContent>
          </Card>
        </main>

        {/* Footer */}
        <footer className="bg-gradient-to-r from-emerald-800 to-green-800 text-white py-12 mt-20">
          <div className="max-w-4xl mx-auto text-center px-4">
            <h3 className="text-2xl font-bold mb-4">Ready to build something amazing?</h3>
            <p className="text-emerald-200 mb-6">
              Join thousands of developers using MagicUI to create beautiful interfaces
            </p>
            <Link href="/playground">
              <Button
                size="lg"
                className="bg-white text-emerald-800 hover:bg-emerald-50 font-bold px-8 py-4 rounded-2xl transition-all hover:scale-105"
              >
                Get Started Now 🚀
              </Button>
            </Link>
          </div>
        </footer>
      </div>
    </MagicUIProvider>
  )
}
